[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "hanze-eqtl-master"
authors = [{name = "royoelen", email = "roy.oelen@gmail.com"}]
dynamic = ["version", "description"]
